# Generated by Django 6.0.5 on 2026-05-20 06:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('game_title', models.CharField(max_length=100)),
                ('format_type', models.CharField(choices=[('single_elimination', 'Single Elimination'), ('round_robin', 'Round Robin')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('registration_open', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
