# Generated by Django 6.0.5 on 2026-06-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='registration',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
