# Generated by Django 6.0.5 on 2026-06-13 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_registration_options_registration_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('in_game_name', models.CharField(max_length=100)),
                ('game_uid', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('captain', 'Captain'), ('player', 'Player'), ('substitute', 'Substitute')], default='player', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='registrations.team')),
            ],
        ),
    ]
